### ISSUE TITLE
Migrate Terraform off DataCite stack 

### ISSUE THREAD

**Issue by mariagould** [ror-community/deployment#4]
- [ ] Investigate current redirect from ror.community to ror.org

- [ ] Investigate current problem with http://www.ror.org not redirecting properly

**Comment by eshadatta-crossref** [comment]
Tasks:
1. Create a parallel system first
  - VPC, DNS, SSL certs, create parallel system under a different name (temporarily)
  - Problem is that there is only one place that manages the DNS. The current terraform manages all the DNS. 

Solution:
1. Start new repo and re-build deployment to reflect cloud Terraform ROR stack. Build a system in parallel with the ror-community domain, test it for about a week, and slowly port over the needed infrastructure to re-create existing services with the existing domain.
